name: Auto-labeling issue
on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get labels
        id: labels
        run: |
          LABELS=$(gh label list)
          echo "available_labels=$LABELS" >> $GITHUB_OUTPUT
          
      - name: Install LangChain CLI
        run: |
          dotnet tool install --global langchain.cli --prerelease
          langchain auth openai ${{ secrets.OPENAI_API_KEY }}

      - name: Analyse issue
        id: analyse
        run: |
          $ARGUMENTS=$(langchain generate --input "Return arguments for `gh issue edit $ISSUE_URL $ARGUMENTS_WILL_BE_HERE$` for issue with these data:\nTitle: ${{ github.event.issue.title }}\nBody: ${{ github.event.issue.body }}\n Available labels: ${{ steps.labels.outputs.available_labels }}\n\nIMPORTANT: Return ONLY replacement for $ARGUMENTS_WILL_BE_HERE$. It should contains one or more --add-label arguments")
          echo "arguments=$ARGUMENTS" >> $GITHUB_OUTPUT

      - env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL ${{ steps.analyse.outputs.arguments }}
